### ISSUE TITLE
Get active friends from specific hotspot Error

### ISSUE THREAD

**Issue by boaerosuke** [IoSL-INav/project#100]
request returns 501 unimplemented

HTTP 501 Unimplemented

Content-Length: 0
X-Powered-By: Express
Connection: keep-alive
Date: Sun, 17 Jan 2016 16:49:34 GMT

**Comment by numbleroot** [comment]
Closed due to commit https://github.com/IoSL-INav/backend@e1ab079ee755fb0d838285a91bb9a9c6c4588bff
