### ISSUE TITLE
Send Friend Request//Add Friend// CompanionRequest

### ISSUE THREAD

**Issue by boaerosuke** [IoSL-INav/project#101]
Just to remind that it is still open

**Comment by boaerosuke** [comment]
Problem was the Federation Provider does not handle the given tubit-email address at this point. The request should also answer with (person found/person not found)

**Comment by hechi** [comment]
it works for me!
post request to /companionrequest with
{
 "userID":"062fd24a-a14d-4aee-bc7c-fe0b77a922d3"
}

**Comment by hechi** [comment]
this is my own userID and then i can see companionrequest with a GET under /companionrequests

**Comment by boaerosuke** [comment]
Sure, but where do I get the userID from somebody else? In order to send him a friend request?
{
"userID":"_somebodyelsesID_"
}

**Comment by hechi** [comment]
normally you get a emailadress but for now we don't get them, you have to ask someone for his userID ^^

**Comment by boaerosuke** [comment]
Okay, and when will the Federation Provider functionality be ready for us in order to use the emailaddress? (I don´t know how you guys can influence this)

**Comment by numbleroot** [comment]
We cannot at all. How should we know? We discussed that yesterday.

**Comment by boaerosuke** [comment]
I did not get that "we will not be able to use email at all" yesterday. I thought it is just a temporary issue. But fine, no email. 

So should we change that in our use cases?
- Alice taps on the button 'Manage friends' and then presses the '+' button. She puts in Bob's tubIT mail address

**Comment by numbleroot** [comment]
No, we need to wait and see if @mathiasslawik will be able to get us name and e-mail via the federation provider. If that is not going to happen, we have to come up with another solution which could get interesting as we don't have too many other options. But let's see, what Mathias says.

**Comment by boaerosuke** [comment]
Sounds good!
