### ISSUE TITLE
iOS CompanionRequest Handling

### ISSUE THREAD

**Issue by boaerosuke** [IoSL-INav/project#102]
Implementation to send and receive Friend Requests not possible yet (waiting for backend)

**Comment by hechi** [comment]
should work i tested it... you can test it with your own userID

**Comment by boaerosuke** [comment]
## Workaround for Demo:

https://federation.cyclone-project.eu/auth/realms/master/account

## If you login you get to a screen where you can manually put in your email address. This adress will be contained in the identity token you get from the Federation Provider and be ready for you to use in the demo.

Right now I don´t know what you need to do/work/change on the backend to make this work

**Comment by mathiasslawik** [comment]
For the backend part you'd need to retrieve the email JWT claim from the identity token you get after login. I'd propose to persist it to the database.

**Comment by numbleroot** [comment]
We did that. Closing.
