### ISSUE TITLE
Define Beacons For Hotspots

### ISSUE THREAD

**Issue by boaerosuke** [IoSL-INav/project#104]
Define all the beacons we will use for each hotspot

**Comment by boaerosuke** [comment]
This is for production.

**Comment by hechi** [comment]
??? we have 4 right now for the mensa... how many did you want for the mensa?

**Comment by boaerosuke** [comment]
I thought we had 10-13 Beacons that we could use for both floors on the mensa (as mr. zickau mentioned). Or are we planning to use only 4 nearables for the whole mensa?!

**Comment by hechi** [comment]
no 4 is not enough but you can use it theoretically to build your app... there are real coordination in the database,... you can turn on one of the beacons and your phone can detect it and the backend give you the location (real long,lat) back (but first we have to do this issue https://github.com/IoSL-INav/project/issues/105#issuecomment-172392158)

**Comment by boaerosuke** [comment]
Yeah makes sense. Let´s deal with it later.

**Comment by hechi** [comment]
Ok we have enough beacons right? at least for the demo. if yes close the issue plz
