### ISSUE TITLE
Beacon UniqueIdentifier Issue

### ISSUE THREAD

**Issue by boaerosuke** [IoSL-INav/project#105]
As the Estimote Documentation states:
Each Beacon MUST have a different ID (not major/minor) in order to monitor multiple beacons. Otherwise the SDK will handle each beacon as the same beacon.

**Comment by hechi** [comment]
you mean this UUIDs?

**Comment by hechi** [comment]
https://github.com/IoSL-INav/project/blob/master/estimote/nearables-info.txt

**Comment by boaerosuke** [comment]
yup the UUID

**Comment by hechi** [comment]
hey elukau, the beacons have now unique id's right? if yes close the issue plz
