### ISSUE TITLE
Notes on updating location

### ISSUE THREAD

**Issue by jmezna** [IoSL-INav/project#108]
I would say that when updating location, backend should update location only if newly sent location is as precise or more precise as location already saved in backend.

Example:
I start with no location. I walk into mensa, MSI API tells me I am in mensa, I send building name and floor to backend. Because I don't have any location saved in backend, backend saves building name and floor as my location. Then I walk pass beacon, send minor and major to backend. Because beacon location is more accurate that only building name and floor, backend updates my location. Then I walk pass another beacon, send major and minor to backend. Because the location info has same accuracy as the last info saved, backend saves the new location info. Then my MSI detecting service run again and says I am in mensa. I send that info to backend. Because that info is less accurate that info already stored (major minor) backend doesn't update my location. Then I decide I will pinpoint my position. I send coordinated to backend. Because coordinates are more accurate that info saved in backend (major minor), backend updates my location info to sent coordinates.

Could you implement such behaviour?

**Comment by hechi** [comment]
Ok what if you go then from the mensa to the library and pin point you there? And what if you want to move on again and don't want the pin pointing any more? do you have to delete it?

**Comment by jmezna** [comment]
If I go to te library and send building/floor, backend could change my location, because I am not in mensa anymore.

I don't know for the second case.

But do you see the problem we have to solve somehow, on device or on in backend? If I have only MSI API I should use that. If I have MSI API and beacon maj/min, I should use maj/min. If I have MSI API, beacon, and coordinates, I should use coordinates.

One solution would be, that I perform scanning for MSI and beacons in one service. This way I can only send beacon info to backend, if I have both. But what happens when I manually pinpoint my coordinates? Should I stop the scanning service for n minutes? 

I am just brainstorming.

Any ideas?

**Comment by hechi** [comment]
hmmm.... i am not sure if its only a backend or a frontend part. but somehow you have to decide in the frontend what do you want to send right? or do you try to send all?

**Comment by numbleroot** [comment]
A possible flow for backend could look like:
- If there is no location when receiving an update: save that location
- If there is one
  - and the new one belongs to a different hotspot: save new location regardless of old location
  - and the new one belongs to same hotspot
    - and is more accurate than old one: save new location
    - and is less accurate than old one: discard update

That way you could send whenever you receive a location update on client side.

**Comment by jmezna** [comment]
I also found a way to do it on client (probably). I will just always store all available info and send the most precise one. Which way should we do it?

**Comment by numbleroot** [comment]
Okay, after today's discussion we decided to go for "preprocessing" available information on client side and updating location on backend with whatever valid information is sent.
