### ISSUE TITLE
Federation Provider (Workaround Issue)

### ISSUE THREAD

**Issue by boaerosuke** [IoSL-INav/project#119]
After submitting additional Information to the federation Provider via:

 https://federation.cyclone-project.eu/auth/realms/master/account/

users/me still gives me not more than this as response:

{
  "userID" : "08622804-8a4f-4492-b0aa-d8257a3db690",
  "userName" : "edugain.afe794459df978974faeabd8619c51d322203fc1"
}

**Comment by hechi** [comment]
This is what i got from ...

**Comment by hechi** [comment]
http://piazza.snet.tu-berlin.de/users/me
{
"userID":"47f583f0-dd02-40d8-a6fc-03a1165a5e0",
"userName":"edugain.ead1e3483726294b60540d57463a6726ee95",
"userEmail":"blabla@campus.tu-berlin.de"
}

**Comment by jmezna** [comment]
I get "email already exist" problem and response for /users/me is

{
"userID": "4e357f3b-ef70-48c4-93b8-020e73fc65d7"
"userName": "edugain.3134883dbf778edc93ce4aec8e75352e8f05984b"
}

**Comment by hechi** [comment]
use another email address

**Comment by jmezna** [comment]
funny story, did that right now, but still don't see it on /users/me :D

**Comment by hechi** [comment]
that could be a caching stuff

**Comment by boaerosuke** [comment]
I tried to logout and login 
Logout via Browser:
does not change anything in the response of the get /users/me response

Logout via Client
 GET /users/me/logout is currently not working (Response: Cannot GET /users/me/logout)

**Comment by numbleroot** [comment]
@hechi and me worked something around that issue today. Tested it, should be fixed.
