### ISSUE TITLE
Research on Indoor-Location

### ISSUE THREAD

**Issue by boaerosuke** [IoSL-INav/project#15]

**Comment by jmezna** [comment]
Book Location-Based Services has chapter about Short range positioning technologies. It covers:
- WiFi based positioning
- Bluetooth technology positioning
- RFID positioning
- other non radio signal technologies (infrared, ultrasound, UWB, dead reckoning)

I can (will)  sum up the chapter in documentation.

Now looking at other research,

**Comment by jmezna** [comment]
WiFi or beacons for location based services?

"Could WiFi work with Beacons?

When technologies meet and work together they often can become more powerful. In the future we predict WiFi and Beacons working together in spaces. With WiFi providing both guest WiFi, analytics and a holistic macro location solution and beacons providing micro location information – when someone is using the relevant brand’s application."

http://www.purplewifi.net/wifi-or-beacons-for-location-based-services/

**Comment by boaerosuke** [comment]
As described and discussed in the previews meeting

As discussed in the previews meeting:
Indoor location using wireless signals might be a "hard to solve task" regarding to distractions of the indoor-location we use the app (Library, Mensa) This is due to different distractions which has effects on the received signal strength.

This might be difficult to implement for our cases.

Find out more here:
http://mycoordinates.org/indoor-positioning-in-wireless/

**Comment by jmezna** [comment]
An Indoor Bluetooth-based positioning system-concept, Implementation and experimental evaluation - This paper presents the experimental evaluation of
a Bluetooth-based positioning system
