### ISSUE TITLE
Create User-Stories/Use-Cases

### ISSUE THREAD

**Issue by boaerosuke** [IoSL-INav/project#18]

**Comment by numbleroot** [comment]
Sorry, @hechi and me are going to work on this one.

**Comment by hechi** [comment]
User story: a definition what a actor(person) want to do or what he wants to achieve. this will mostly written down in one sentence. e.g.
`"As a <type of user>, I want <some goal> so that <some reason>."`

Use case: defines a single action sequence between actor(person) and software.

**Comment by numbleroot** [comment]
Done. Please find our propositions [here](https://github.com/IoSL-INav/project/blob/master/user-stories-and-use-cases/user-stories-and-use-cases.md).
