### ISSUE TITLE
draw technology matrix

### ISSUE THREAD

**Issue by hechi** [IoSL-INav/project#30]
accuracy, user interaction, battery, privacy, platform

**Comment by boaerosuke** [comment]
This should be discussed. It´s a pdf file that can be included into the tex.

**Comment by hechi** [comment]
elukau can you reference to an commit msg in the other project?

**Comment by hechi** [comment]
i added your picture to the slides

**Comment by numbleroot** [comment]
What about 'security/privacy' as a criteria? And I think, we should be using BLE as the technology's name not iBeacon.
