### ISSUE TITLE
Testing CISCO MSE

### ISSUE THREAD

**Issue by boaerosuke** [IoSL-INav/project#49]
Weitere Tests beim API aufruf
- MENSA
- Bibliothek

**Comment by boaerosuke** [comment]
Problem with the empty coordinates: We might add the card material into the Cisco-MSE system.

Info changedOn="2015-11-10T11:31:31.696+0100" confidenceFactor="48.0" building="Mensa" floor="Mensa 1. OG" WLAN-Status="EDUROAM" username="elukau2912@win.tu-berlin.de" lon="" lat=""

**Comment by elukau** [comment]
<Info changedOn="2015-11-10T11:31:31.696+0100" confidenceFactor="48.0" building="Mensa" floor="Mensa 1. OG" WLAN-Status="EDUROAM" username="elukau2912@win.tu-berlin.de" lon="" lat=""/>

**Comment by elukau** [comment]
"<Info changedOn="2015-11-10T11:31:31.696+0100" confidenceFactor="48.0" building="Mensa" floor="Mensa 1. OG" WLAN-Status="EDUROAM" username="elukau2912@win.tu-berlin.de" lon="" lat=""/>"

**Comment by jmezna** [comment]
Do we really need coordinates in mensa/bibliothek? Isn't floor information enough and beacons take it from here?

**Comment by boaerosuke** [comment]
Depends on what we want to do. If we want to locate our selfs on the device, then we should use the MSE API Coords.  If not the floor information provided by MSE API will be sufficient. This can also be stored together with the beacon ID on our server so we can download it. But this approach will be completely without coordinates then.

**Comment by numbleroot** [comment]
The idea was to use the MSE API to get the rough location (building, floor) of a connecting user and after that use locally available beacons or other precise techniques to locate the user inside a room. For that setup we would not need to have coordinates from the API universally available.

**Comment by boaerosuke** [comment]
Ah okay, that was the Idea I was following. But while testing the last days I was a bit confused about something:

We do all this MSE, Federationprovider, tubit-token, openID,webview-browser-url stuff  just to show a user (who is currently in the mensa looking for friends) in which building he is and on which floor he is?
