### ISSUE TITLE
Meet up with Herr Zimmermann

### ISSUE THREAD

**Issue by boaerosuke** [IoSL-INav/project#50]
Personal Talk with Mr. Zimmermann from TUBIT, I think he has no Idea what we want to to.

**Comment by boaerosuke** [comment]
We need to meet Mr. Zimmermann regarding the MSE-API Issue. There are some serious issues we need to clear before we can move on with development.

**Comment by numbleroot** [comment]
Note from today's meeting:
We should ask Mr. Zimmerman who is completely responsible for the Cisco MSE API and would be able to provide us with information regarding coordinates.
Then we should go talk to that person.
