### ISSUE TITLE
Rework Map Material

### ISSUE THREAD

**Issue by boaerosuke** [IoSL-INav/project#53]
Rework the Material to make it work as overlay on Mobiledevices

**Comment by hechi** [comment]
elukau what did you mean with rework?

**Comment by boaerosuke** [comment]
The maps from Mensa or the Library will need to be redrawn and cleaned up in order to be shown correctly on the mobile device. 
I will do this while development

**Comment by hechi** [comment]
okay which technology do you want to use?

**Comment by boaerosuke** [comment]
To put our map in to a mapview on a device we need to render it as an overlay. This will need to be based on vector graphics to be scaleable, then we will need the correct pixel positions to calculate them to the coordinate system of the underlying mapview. So that each coordinate has its belonging pixel position. Then that map has to have the correct size and orientation, based on the exact size of the building. Therefore I will open the pdfs and cut some irrelevant stuff of scale and clean it. Render it as pdf but getting the correct anchor-pixels. This will be needed to have at least two anchor-pixels on the map that the device can use to calculate the coordinates correctly. (that´s why I went to the mensa yesterday the whole day to find out which coordinate could be  which point on the pdf file).  

This is important because only after this works we will be finally able to see how our ideas work and if the signal is strong enough to see our self on the map.

**Comment by boaerosuke** [comment]
added additional Hotspot Information as Annotations (Cash Register, Foodstands, Stairs, Windows)
