### ISSUE TITLE
make research on cyclone

### ISSUE THREAD

**Issue by hechi** [IoSL-INav/project#56]

**Comment by hechi** [comment]
# How does the OpenID Connect flow works

## 3.1.1.  Authorization Code Flow Steps

The Authorization Code Flow goes through the following steps.

Client prepares an Authentication Request containing the desired request parameters.
Client sends the request to the Authorization Server.
Authorization Server Authenticates the End-User.
Authorization Server obtains End-User Consent/Authorization.
Authorization Server sends the End-User back to the Client with an Authorization Code.
Client requests a response using the Authorization Code at the Token Endpoint.
Client receives a response that contains an ID Token and Access Token in the response body.
Client validates the ID token and retrieves the End-User's Subject Identifier.

### PRO:
- they will do the authorization

### CON:
- we have to hold them as well (no benefit)
- more protocols to know
- we can not search for users or ask if they exists

### notes
- setup keycloak with cyclone-project as a federation provider (https://github.com/cyclone-project/cyclone-federation-provider)
- keycloak is written in java
- Docu and Videos for keycloak is here http://keycloak.jboss.org/docs
- keycloak uses SAML
- JWT = JSON Web Token

### Questions
- how can we connect to the tubit authentication?
- can we get information of other users?
- how can we verify that the user is still logged in and its valid? 

### how i get it
- our users want to authenticate
- they will redirected to a federation-provider
- the federation-provider will redirect to the authentication-server
- every thing goes back with a JWT
- we get the JWT and its done

user -> our server -> federation provider -> authentication server

-> represent a redirect

**Comment by mathiasslawik** [comment]
You do not need to "connect" to TUBit authentication. If you want them to automatically redirect, use the "kc_idp_hint" parameter. I'll ask Ömer what value you need to set for TUBit.

You cannot get information of other users when they have not logged in yet (just as you would if you handle the authentication yourself)

You can veryfy that the user is still logged in via the refresh token.

**Comment by hechi** [comment]
but we have to setup cyclone by our self right?

**Comment by mathiasslawik** [comment]
I think you're misrepresenting the cons:

-> we have to hold them as well (no benefit)

There are many benefits: You do not need to implement a password database, a password reset function, a password forget function, protection against brute force attacks, a registration workflow, a confirmation workflow, an "edit my information" screen, an email validation, etc. Also, your users have one less password to remember. Furthermore, they don't need to add their information manually, as their display name, their email, etc is all transmitted to you for free.

more protocols to know

You do not need to implement OpenID Connect, as there are many libraries already available.

we can not search for users or ask if they exists

You can always query your own database.

**Comment by mathiasslawik** [comment]
You only need to integrate an existing OpenID Connect library into your backend, as well as implementing some short methods, such as: "Create user (if not exists) based on Identity Token", etc.

**Comment by hechi** [comment]
ahh... okay this is nice
and the client also need a OpenID Connect library right?

**Comment by mathiasslawik** [comment]
What do you mean by "client"?

**Comment by hechi** [comment]
android-client or ios-client

**Comment by mathiasslawik** [comment]
No. OpenID Connect is browser-based, so you need to handle the authentication flow within a web view and then extract the cookie or make a redirect to an Android-registered URL.

**Comment by hechi** [comment]
okay and why should we use a OpenID Connect lib in the backend? Only for the refresh token right?

**Comment by mathiasslawik** [comment]
Also for retrieving the identity token with the access code you get from the Authentication Web Flow.

**Comment by hechi** [comment]
done
