### ISSUE TITLE
Backend - start implementing tests for API controllers

### ISSUE THREAD

**Issue by numbleroot** [IoSL-INav/project#76]

**Comment by numbleroot** [comment]
@hechi We should not forget this.

**Comment by numbleroot** [comment]
"Parameterize server app to use a testing config and then use a mockup authentification for testing."

**Comment by numbleroot** [comment]
@hechi: Done, right?

**Comment by hechi** [comment]
jup done, i did 10 tests, but no tests for companienrequest and share location stuff
