### ISSUE TITLE
Add names of friends

### ISSUE THREAD

**Issue by boaerosuke** [IoSL-INav/project#97]
The clear name of a friend that will be shown in the app

**Comment by boaerosuke** [comment]
Federation Provider is unable to return clear names.

**Comment by boaerosuke** [comment]
We need to find a proper solution for this issue. Just naming every friend "anonymous" is not sufficient in my opinion.

**Comment by hechi** [comment]
you can give you a own name by update /user/me
i think @numbleroot knows how

**Comment by numbleroot** [comment]
PUT on /users/me with body looking like:
`{ "userName": "Bernd" }`

See: https://github.com/IoSL-INav/project/blob/master/ideas-and-approaches/DraftOfApi.md#change-user-information

**Comment by boaerosuke** [comment]
So at least I´ll get my own name :D. Well thx for the hint, however if I´ll find time I´ll need to implement a client side solution for this.

**Comment by numbleroot** [comment]
Simple option in user settings view.
